### ISSUE TITLE
mosquitto 2.0.11 failed to build osx

### ISSUE THREAD

**Issue by chenrui333** [eclipse/mosquitto#2227]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -bundle -Wl,-headerpad_max_install_names -o mosquitto_payload_modification.so CMakeFiles/mosquitto_payload_modification.dir/mosquitto_payload_modification.c.o   -L/tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11
Undefined symbols for architecture x86_64:
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in mosquitto_message_timestamp.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in mosquitto_message_timestamp.c.o
  "_mosquitto_property_add_string_pair", referenced from:
      _callback_message in mosquitto_message_timestamp.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/message-timestamp/mosquitto_message_timestamp.so] Error 1
make[1]: *** [plugins/message-timestamp/CMakeFiles/mosquitto_message_timestamp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Undefined symbols for architecture x86_64:
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in mosquitto_payload_modification.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in mosquitto_payload_modification.c.o
  "_mosquitto_calloc", referenced from:
      _callback_message in mosquitto_payload_modification.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/payload-modification/mosquitto_payload_modification.so] Error 1
make[1]: *** [plugins/payload-modification/CMakeFiles/mosquitto_payload_modification.dir/all] Error 2
...

cd /tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11/src && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DCMAKE -DVERSION=\"2.0.11\" -DWITH_BRIDGE -DWITH_BROKER -DWITH_CONTROL -DWITH_EC -DWITH_MEMORY_TRACKING -DWITH_PERSISTENCE -DWITH_SOCKS -DWITH_SYS_TREE -DWITH_THREADING -DWITH_TLS -DWITH_TLS_PSK -DWITH_UNIX_SOCKETS -DWITH_WEBSOCKETS -I/tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11 -I/tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11/src -I/tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11/include -I/tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11/lib -I/tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11/deps -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -MD -MT src/CMakeFiles/mosquitto.dir/handle_connack.c.o -MF CMakeFiles/mosquitto.dir/handle_connack.c.o.d -o CMakeFiles/mosquitto.dir/handle_connack.c.o -c /tmp/mosquitto-20210611-88199-12d530o/mosquitto-2.0.11/src/handle_connack.c
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_f_base64", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_free_all", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_new", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_push", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_read", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_s_mem", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_set_flags", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_write", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_EVP_get_digestbyname", referenced from:
      _dynsec_auth__pw_hash in auth.c.o
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _dynsec_auth__pw_hash in auth.c.o
  "_RAND_bytes", referenced from:
      _dynsec_auth__pw_hash in auth.c.o
  "_mosquitto_broker_publish", referenced from:
  "_mosquitto_log_printf", referenced from:
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_delete in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      ...
  "_mosquitto_malloc", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clientlist__add in clientlist.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _dynsec_grouplist__add in grouplist.c.o
      ...
  "_mosquitto_strdup", referenced from:
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_groups__process_modify in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
  "_mosquitto_sub_topic_check", referenced from:
      _dynsec_roles__process_add_acl in roles.c.o
      _dynsec_roles__process_remove_acl in roles.c.o
  "_mosquitto_topic_matches_sub", referenced from:
      _acl_check_publish_c_send in acl.c.o
      _acl_check_publish_c_recv in acl.c.o
  "_mosquitto_validate_utf8", referenced from:
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_clients__process_get in clients.c.o
      ...
ld: symbol(s) not found for architecture x86_64
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/2799829385
relates to Homebrew/homebrew-core#79126

**Comment by chenrui333** [comment]
Can I get some help on this? Thanks!

**Comment by ralight** [comment]
I believe this is now fixed in c01ae67af717e69c5225aaba3f3b50e7c5d0bdae which will be part of 2.0.12 soon.

**Comment by chenrui333** [comment]
Let me also give that patch commit a try.

**Comment by chenrui333** [comment]
I got the new build failure after applying the patch

```
Undefined symbols for architecture x86_64:
  "_mosquitto_broker_publish", referenced from:
      _send_response in plugin.c.o
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in plugin.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in plugin.c.o
  "_mosquitto_calloc", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
  "_mosquitto_client_id", referenced from:
      _dynsec_auth__basic_auth_callback in auth.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_delete in clients.c.o
  "_mosquitto_strdup", referenced from:
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_groups__process_modify in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
  "_mosquitto_sub_topic_check", referenced from:
      _dynsec_roles__process_add_acl in roles.c.o
      _dynsec_roles__process_remove_acl in roles.c.o
  "_mosquitto_topic_matches_sub", referenced from:
      _acl_check_publish_c_send in acl.c.o
      _acl_check_publish_c_recv in acl.c.o
  "_mosquitto_validate_utf8", referenced from:
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_clients__process_get in clients.c.o
      ...
ld: symbol(s) not found for architecture x86_64
~``

**Comment by chenrui333** [comment]
cc @ralight

**Comment by chenrui333** [comment]
The latest 2.0.12 still failed to build on osx.
https://github.com/Homebrew/homebrew-core/pull/84522

```
Undefined symbols for architecture x86_64:
  "_mosquitto_broker_publish", referenced from:
      _send_response in plugin.c.o
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in plugin.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in plugin.c.o
  "_mosquitto_calloc", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
  "_mosquitto_client_id", referenced from:
      _dynsec_auth__basic_auth_callback in auth.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_delete in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      ...
  "_mosquitto_client_username", referenced from:
      _acl_check in acl.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_delete in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      ...
  "_mosquitto_free", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
      _client__free_item in clients.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__config_save in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      ...
  "_mosquitto_kick_client_by_username", referenced from:
      _dynsec_clients__process_delete in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_clients__process_add_role in clients.c.o
      _dynsec_clients__process_remove_role in clients.c.o
      ...
  "_mosquitto_log_printf", referenced from:
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_delete in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      ...
  "_mosquitto_malloc", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clientlist__add in clientlist.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _dynsec_grouplist__add in grouplist.c.o
      ...
  "_mosquitto_strdup", referenced from:
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_groups__process_modify in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
  "_mosquitto_sub_topic_check", referenced from:
      _dynsec_roles__process_add_acl in roles.c.o
      _dynsec_roles__process_remove_acl in roles.c.o
  "_mosquitto_topic_matches_sub", referenced from:
      _acl_check_publish_c_send in acl.c.o
      _acl_check_publish_c_recv in acl.c.o
  "_mosquitto_validate_utf8", referenced from:
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
      _dynsec_clients__process_modify in clients.c.o
      _dynsec_clients__process_get in clients.c.o
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by chenrui333** [comment]
ping @ralight

**Comment by liuwuhaoo** [comment]
I also got this error with macOS.
