### ISSUE TITLE
mosquitto 1.5 fails to build with -DUSE_LIBWRAP:STRING=ON

### ISSUE THREAD

**Issue by tgurr** [eclipse/mosquitto#844]
Installed tcp-wrappers version is 7.6.
```
[...]
[ 73%] Building C object src/CMakeFiles/mosquitto.dir/__/lib/net_mosq.c.o
cd /var/tmp/paludis/build/net-mosquitto-1.5-r1/work/build/src && /usr/bin/x86_64-pc-linux-gnu-cc -DCMAKE -DHAVE_GETADDRINFO_A -DVERSION=\"1.5.0\" -DWITH_BRIDGE -DWITH_BROKER -DWITH_EC -DWITH_MEMORY_TRACKING -DWITH_PERSISTENCE -DWITH_SOCKS -DWITH_SYS_TREE -DWITH_TLS -DWITH_TLS_PSK -DWITH_UUID -DWITH_WRAP -I/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5 -I/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5/src -I/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5/lib  -march=native -O2 -pipe   -o CMakeFiles/mosquitto.dir/__/lib/net_mosq.c.o   -c /var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5/lib/net_mosq.c
/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5/src/net.c: In function 'net__socket_accept':
/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5/src/net.c:117:7: warning: implicit declaration of function 'mosquitto__socket_get_address'; did you mean 'net__socket_get_address'? [-Wimplicit-function-declaration]
   if(!mosquitto__socket_get_address(new_sock, address, 1024)){
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       net__socket_get_address
[...]
```
```
[...]
[100%] Linking C executable mosquitto
cd /var/tmp/paludis/build/net-mosquitto-1.5-r1/work/build/src && /usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/mosquitto.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-cc -march=native -O2 -pipe  -rdynamic -Wl,-dynamic-list=/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/mosquitto-1.5/src/linker.syms CMakeFiles/mosquitto.dir/conf.c.o CMakeFiles/mosquitto.dir/conf_includedir.c.o CMakeFiles/mosquitto.dir/context.c.o CMakeFiles/mosquitto.dir/database.c.o CMakeFiles/mosquitto.dir/handle_connack.c.o CMakeFiles/mosquitto.dir/handle_connect.c.o CMakeFiles/mosquitto.dir/__/lib/handle_ping.c.o CMakeFiles/mosquitto.dir/__/lib/handle_pubackcomp.c.o CMakeFiles/mosquitto.dir/handle_publish.c.o CMakeFiles/mosquitto.dir/__/lib/handle_pubrec.c.o CMakeFiles/mosquitto.dir/__/lib/handle_pubrel.c.o CMakeFiles/mosquitto.dir/__/lib/handle_suback.c.o CMakeFiles/mosquitto.dir/handle_subscribe.c.o CMakeFiles/mosquitto.dir/__/lib/handle_unsuback.c.o CMakeFiles/mosquitto.dir/handle_unsubscribe.c.o CMakeFiles/mosquitto.dir/logging.c.o CMakeFiles/mosquitto.dir/loop.c.o CMakeFiles/mosquitto.dir/__/lib/memory_mosq.c.o CMakeFiles/mosquitto.dir/mosquitto.c.o CMakeFiles/mosquitto.dir/net.c.o CMakeFiles/mosquitto.dir/__/lib/net_mosq.c.o CMakeFiles/mosquitto.dir/__/lib/packet_mosq.c.o CMakeFiles/mosquitto.dir/persist.c.o CMakeFiles/mosquitto.dir/plugin.c.o CMakeFiles/mosquitto.dir/read_handle.c.o CMakeFiles/mosquitto.dir/subs.c.o CMakeFiles/mosquitto.dir/security.c.o CMakeFiles/mosquitto.dir/security_default.c.o CMakeFiles/mosquitto.dir/__/lib/send_mosq.c.o CMakeFiles/mosquitto.dir/send_connack.c.o CMakeFiles/mosquitto.dir/__/lib/send_connect.c.o CMakeFiles/mosquitto.dir/__/lib/send_disconnect.c.o CMakeFiles/mosquitto.dir/__/lib/send_publish.c.o CMakeFiles/mosquitto.dir/send_suback.c.o CMakeFiles/mosquitto.dir/signals.c.o CMakeFiles/mosquitto.dir/__/lib/send_subscribe.c.o CMakeFiles/mosquitto.dir/__/lib/send_unsubscribe.c.o CMakeFiles/mosquitto.dir/sys_tree.c.o CMakeFiles/mosquitto.dir/__/lib/time_mosq.c.o CMakeFiles/mosquitto.dir/__/lib/tls_mosq.c.o CMakeFiles/mosquitto.dir/__/lib/util_mosq.c.o CMakeFiles/mosquitto.dir/__/lib/utf8_mosq.c.o CMakeFiles/mosquitto.dir/websockets.c.o CMakeFiles/mosquitto.dir/__/lib/will_mosq.c.o CMakeFiles/mosquitto.dir/bridge.c.o  -o mosquitto -Wl,-rpath,:::::::::::::::::::::::::::: -lwrap -lssl -lcrypto -lanl -ldl -lm -lrt -luuid 
make[2]: Leaving directory '/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/net-mosquitto-1.5-r1/work/build'
CMakeFiles/mosquitto.dir/net.c.o: In function `net__socket_accept':
net.c:(.text+0x7a6): undefined reference to `mosquitto__socket_get_address'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mosquitto.dir/build.make:749: src/mosquitto] Error 1
make[1]: *** [CMakeFiles/Makefile2:366: src/CMakeFiles/mosquitto.dir/all] Error 2
make: *** [Makefile:133: all] Error 2
```

**Comment by Tifaifai** [comment]
resolved in https://github.com/eclipse/mosquitto/pull/810 PR ;)
in waiting.... ;)

**Comment by tgurr** [comment]
@Tifaifai thanks for the information! Shipping that patch downstream for the time being.

**Comment by Tifaifai** [comment]
Closed ?

**Comment by tgurr** [comment]
The pull request in question hasn't been accepted yet so the issue/bug is still valid.

**Comment by ralight** [comment]
The PR is now merged, could you check the `fixes` branch and close this issue if you're happy?

**Comment by tgurr** [comment]
Sure thing, thanks! Looking forward to a 1.5.x bugfix release and the fixes branch getting merged to master.
